### ISSUE TITLE
NP tag, quick fix

### ISSUE THREAD

**Issue by bramptonjp** [liuch/dmarc-srg#70] opened 2023-06-10 17:40 UTC
You can fix this issue with the following

    260                 'NP'     => 'policy_np'
    292         'policy_np'    => [ 'parent' => 'p_p', 'header' => true, 'default' => null ],

**Comment by liuch** [comment] 2023-06-10 22:41
Duplicate of #68

**Closed by liuch** 2023-06-10 22:41 UTC
