### ISSUE TITLE
JSON.parse: unexpected non-whitespace

### ISSUE THREAD

**Issue by yo3ibw** [liuch/dmarc-srg#117] opened 2024-02-15 19:15 UTC
Hey, I receive this error on moast of the sections of the application,

"JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 33 of the JSON data" (ex: Files + Load Report From Mailboxes, Load Reports)

"Unexpected non-whitespace character after JSON at position 23 (line 1 column 24)" on first page, afrer entering password in the login prompt.

Enviroment: Nginx, PHP 7.4, MySQL 8.0 in Docker,  App Version 1.8 

PS: After recreating the docker containers it started to work.

**Comment by liuch** [comment] 2024-02-16 00:07
It looks like some error text was included in the resulting JSON response. Could you reproduce this error and show me the server response? You can see it in the browser console. Or you can also see it in your server logs.

**Comment by liuch** [comment] 2024-03-29 19:23
I'm closing this then.

**Closed by liuch** 2024-03-29 19:23 UTC
