### ISSUE TITLE
Installing on a shared webhost

### ISSUE THREAD

**Issue by elimae17** [liuch/dmarc-srg#83] opened 2023-07-02 10:03 UTC
Hi,

first of all I want to thank you for this awesome software! 

I  filled out the config file, created an empty an MySQL-Database and copied the files to our shared webhost (Litespeed Webserver with cPanel). However when I log into the admin panel, I get the error "The database schema is not initiated." and it tells me that the tables do not exist. 

In your documentation it says that the Database initialization can either be done via the command shell or the web interface. Because I am on a shared webhost, my hosting provider doesn't grant me access to the command shell so i can't run any PHP commands. Is there any way I can initialize the database without running commands, if necessary even manually by creating the tables?

I would be grateful for any help!

Thanks
Elias

**Comment by williamdes** [comment] 2023-07-02 10:26
Hi
That's a good question, I think this feature is needed !

Meanwhile, you can hack into this file to get it working with a web request: https://github.com/liuch/dmarc-srg/blob/master/utils/database_admin.php#L47

Remove the sapi check or invert the boolean
And the define `$action = 'init';`

That should work

**Comment by liuch** [comment] 2023-07-02 14:59
Hi,
Why don't you consider initializing the database schema via the web interface?

![admin panel screenshot](https://i.imgur.com/WCiO3qu.png)

If your provider does not grant you access to the command shell, how are going to get summary reports without the web interface? In case your provider grants access to cron, you can add a cron job in order to initialize the database schema and then remove it. Perhaps I did not understand the reason for your difficulty, let me know.

**Comment by liuch** [comment] 2023-07-02 15:03
@williamdes, your instruction is missing a "revert code changes you made earlier" clause :)

**Comment by elimae17** [comment] 2023-07-02 16:23
Thank you both for your quick replies!

@liuch I overlooked this function in the web interface. It worked perfectly this way!

**Comment by liuch** [comment] 2023-07-02 17:08
Great. I'm closing this issue then.

**Closed by liuch** 2023-07-02 17:08 UTC

**Comment by williamdes** [comment] 2023-07-02 17:27
> @williamdes, your instruction is missing a "revert code changes you made earlier" clause :)

Ha yes, I was thinking about it but forgot to write it

I did not even know that it was possible !
The first time I did fire the UI it did throw error 500 in XHR requests, so I did the init with the CLI.
Maybe there is still things to fix ?
Or I was missing an extension, most probably.

**Comment by liuch** [comment] 2023-07-02 18:32
I don't know why you were getting error 500. The web interface doesn't require a working database. Perhaps the logs on your web server will clear things up.

**Comment by williamdes** [comment] 2023-07-02 19:30
> I don't know why you were getting error 500. The web interface doesn't require a working database. Perhaps the logs on your web server will clear things up.

Most probably I was missing some php extensions
Maybe it was mysql or imap
 If I can I will try to reproduce this
