### ISSUE TITLE
Error - Bad Message Number

### ISSUE THREAD

**Issue by andrewhenke** [liuch/dmarc-srg#116] opened 2024-01-23 17:57 UTC
When I run the `fetch_reports` utility from the command line, I frequently encounter the following error nearly every single time I fetch the latest reports. 

```
dmarc-srg [error]: ErrorException: imap_fetchstructure(): Bad message number in <REMOVED FOR PRIVACY>/classes/Mail/MailMessage.php:98
Stack trace:
#0 [internal function]: {closure}()
#1 <REMOVED FOR PRIVACY>/classes/Mail/MailMessage.php(98): imap_fetchstructure()
#2 <REMOVED FOR PRIVACY>/classes/Mail/MailMessage.php(71): Liuch\DmarcSrg\Mail\MailMessage->ensureAttachment()
#3 <REMOVED FOR PRIVACY>/classes/Sources/MailboxSource.php(83): Liuch\DmarcSrg\Mail\MailMessage->validate()
#4 <REMOVED FOR PRIVACY>/classes/Report/ReportFetcher.php(121): Liuch\DmarcSrg\Sources\MailboxSource->current()
#5 <REMOVED FOR PRIVACY>/utils/fetch_reports.php(174): Liuch\DmarcSrg\Report\ReportFetcher->fetch()
#6 {main}
-----
Error: imap_fetchstructure(): Bad message number (-1)
-----
ErrorException: imap_fetchstructure(): Bad message number in <REMOVED FOR PRIVACY>/classes/Mail/MailMessage.php:98
Stack trace:
#0 [internal function]: {closure}()
#1 <REMOVED FOR PRIVACY>/classes/Mail/MailMessage.php(98): imap_fetchstructure()
#2 <REMOVED FOR PRIVACY>/classes/Mail/MailMessage.php(71): Liuch\DmarcSrg\Mail\MailMessage->ensureAttachment()
#3 <REMOVED FOR PRIVACY>/classes/Sources/MailboxSource.php(83): Liuch\DmarcSrg\Mail\MailMessage->validate()
#4 <REMOVED FOR PRIVACY>/classes/Report/ReportFetcher.php(121): Liuch\DmarcSrg\Sources\MailboxSource->current()
#5 <REMOVED FOR PRIVACY>/utils/fetch_reports.php(174): Liuch\DmarcSrg\Report\ReportFetcher->fetch()
#6 {main}
```

Please let me know if I can provide any additional information or details!

**Comment by liuch** [comment] 2024-01-23 21:47
Hello,
Could you show me the $fetcher => mailboxes section from your configuration file?

**Comment by andrewhenke** [comment] 2024-01-23 22:14
<img width="602" alt="image" src="https://github.com/liuch/dmarc-srg/assets/24320242/ebe2f487-988c-4204-8fdd-cd96f02d9548">

**Comment by liuch** [comment] 2024-01-24 20:21
Thank you for the information. I have a pair more questions:
- Is it possible that  when this error occurs there were other IMAP sessions where messages were deleted or moved from the mailbox?
- When this error occurs are there any unprocessed mail messages left? If yes, are they correct incoming dmarc reports?

**Comment by bend86** [comment] 2024-02-12 12:25
Dear, 

I add the same problem. I fixed it by working on messages UID instead of sequencial id. (UID order does not change whatever happens).

Adding flags FT_UID, CP_UID, ST_UID to following calls is working for me.

![image](https://github.com/liuch/dmarc-srg/assets/25978947/ce1a6659-e52d-4a9c-ba22-c64b38fccbbf)

**Comment by andrewhenke** [comment] 2024-02-13 14:45
> Thank you for the information. I have a pair more questions:
> 
> - Is it possible that  when this error occurs there were other IMAP sessions where messages were deleted or moved from the mailbox?
> 
> - When this error occurs are there any unprocessed mail messages left? If yes, are they correct incoming dmarc reports?

Hello, and my apologies for the delay in response. 

The imap connection I utilize is only for accessing the DMARC reports and no other connections would be present. 

Likewise, yes, there are outstanding reports to be ingested and they are properly formatted.

**Comment by bend86** [comment] 2024-02-13 17:52
Dear, for me there was only dmarc reports in the mailbox.
It failed systematically, after a few messages parsed (3-4)

The fix by use of UID let me think there could be some shift in the message index when some operations are done.

Hope it helps

**Comment by liuch** [comment] 2024-02-14 22:07
Thank you you all. It looks like some email servers does not don't follow the standard. I'll fix it soon.

**Comment by liuch** [comment] 2024-02-15 00:39
done.

**Comment by andrewhenke** [comment] 2024-02-15 02:34
I'll give it a test it the morning  and let you know how it functions for me!

**Comment by liuch** [comment] 2024-03-05 00:13
Any news on this issue? May I close this?

**Comment by liuch** [comment] 2024-03-29 19:26
I'm closing this then. Feel free to reopen it if the issue is still relevant.

**Closed by liuch** 2024-03-29 19:26 UTC
