### ISSUE TITLE
Unknown tag: NP

### ISSUE THREAD

**Issue by antitbone** [liuch/dmarc-srg#69] opened 2023-06-08 12:28 UTC
Hello,
I have a problem with reports sent by google.

The debug log is as follows:

```
Failed to get incoming report:
  Error message:
    - Unknown tag: NP
  Email message metadata:
    - From:    noreply-dmarc-support@google.com
    - Date:    Wed, 07 Jun 2023 16:59:59 -0700
    - Mailbox: INBOX (Dmarc-Rua)
```

The report email is as follows:
```xml
<feedback>
<report_metadata>
<org_name>google.com</org_name>
<email>noreply-dmarc-support@google.com</email>
<extra_contact_info>https://support.google.com/a/answer/2466580</extra_contact_info>
<report_id>8908642136726780490</report_id>
<date_range>
<begin>1686096000</begin>
<end>1686182399</end>
</date_range>
</report_metadata>
<policy_published>
<domain>exemple.com</domain>
<adkim>r</adkim>
<aspf>r</aspf>
<p>none</p>
<sp>none</sp>
<pct>100</pct>
<np>none</np>
</policy_published>
<record>
<row>
<source_ip>127.0.0.1</source_ip>
<count>2</count>
<policy_evaluated>
<disposition>none</disposition>
<dkim>fail</dkim>
<spf>pass</spf>
</policy_evaluated>
</row>
<identifiers>
<header_from>exemple.com</header_from>
</identifiers>
<auth_results>
<spf>
<domain>exemple.com</domain>
<result>pass</result>
</spf>
</auth_results>
</record>
</feedback>
```

The **np** tag of rfc9091 does not seem to be supported.
```
        'p_p' => [
            'parent' => 'feedback',
            'children' => [
                'DOMAIN' => 'domain',
                'ADKIM'  => 'policy_adkim',
                'ASPF'   => 'policy_aspf',
                'P'      => 'policy_p',
                'SP'     => 'policy_sp',
                'PCT'    => 'policy_pct',
                'FO'     => 'policy_fo'
            ]
```

Antoine

**Comment by liuch** [comment] 2023-06-10 22:40
Duplicate of #68

**Closed by liuch** 2023-06-10 22:40 UTC
