### ISSUE TITLE
Problems with php7.4

### ISSUE THREAD

**Issue by drder66** [liuch/dmarc-srg#17] opened 2022-02-14 17:58 UTC
dmarc-srg was working ok with php7.3. For other reasons, I've had to upgrade to php7.4 and now I get a load of deprecated messages (which i can live with), but finally "SQLSTATE[HY000] [2002] No such file or directory" 
Steps to debug that would be appreciated. Thanks.

PHP Deprecated:  Return type of Liuch\DmarcSrg\Sources\Source::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/dmarc-srg-master/classes/Sources/Source.php on line 60

Deprecated: Return type of Liuch\DmarcSrg\Sources\Source::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/dmarc-srg-master/classes/Sources/Source.php on line 60
PHP Deprecated:  Return type of Liuch\DmarcSrg\Sources\Source::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/dmarc-srg-master/classes/Sources/Source.php on line 61

Deprecated: Return type of Liuch\DmarcSrg\Sources\Source::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/dmarc-srg-master/classes/Sources/Source.php on line 61
PHP Deprecated:  Return type of Liuch\DmarcSrg\ReportFile\ReportGZFileCutFilter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/dmarc-srg-master/classes/ReportFile/ReportGZFileCutFilter.php on line 33

Deprecated: Return type of Liuch\DmarcSrg\ReportFile\ReportGZFileCutFilter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/dmarc-srg-master/classes/ReportFile/ReportGZFileCutFilter.php on line 33
SQLSTATE[HY000] [2002] No such file or directory

**Comment by liuch** [comment] 2022-02-15 13:52
Hello drder66,
Thank you for your report.

> PHP Deprecated: Return type of...

The thing is, I also have php7.4 on my desktop and I don't see these warnings.

````
$ php -v
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )
````
Are you sure you are using php7.4? Can you explain to me how and where do you see these warnings with Deprecated?


> SQLSTATE[HY000] [2002] No such file or directory

Try using `127.0.0.1` instead of `localhost` in your database connection settings. If it doesn't work, open the php.ini file and find this line: `mysql.default_socket`. Check the path to the mysql.sock file.

**Comment by drder66** [comment] 2022-02-15 17:41
My bad. 
On the same machine Apache is using php7.4, but the cli is using php8.1 
> php -v
PHP 8.1.2 (cli) (built: Jan 27 2022 12:20:56) (NTS)
Copyright (c) The PHP Group

If I force dmarc-srg to use php7.4 then it works as expected. Using php8.1 reveals the deprecated messages and the SQL error
Thanks
Derek

**Comment by liuch** [comment] 2022-02-15 17:47
You're welcome. I'll fix the warnings `Deprecated` anyway. As for the SQL error, I think that the problem is different.

**Comment by liuch** [comment] 2022-02-15 19:51
I have just committed some fixes about this. Could you check out the warnings with your php8?

**Comment by drder66** [comment] 2022-02-15 21:46
At the moment, your latest version is running clean with 8.1. I don't have any dmarc reports to process though; I should have some tomorrow. 
Thanks

**Closed** 2022-04-17 19:47 UTC
